/*
// Pulp Fiction
// Game by Alex Groff and Gavin Concepcion

// This game adapts the 1994 film Pulp Fiction by Quentin Tarantino.
The game follows a consistent gameplay style throughout each level, where you must get your car to a destination while avoiding obstacles.
The car obstacles are randomly generated by Phaser. The enemies also have detection zones from Phaser.

// Level 1 is based off of the opening car ride to the apartment between Jules Winnfield and Vincent Vega.
The level introduces you to the game and the controls, much like how the scene its based on introduces our main leads.

// Level 2 adapts the scene where Mia is dying from an overdose and Vincent has to rush her to Lance's.
In the level, you have to get to the destination before time runs our in the dark streets of Los Angeles.
The level showcases our time feature for the first time as well as a camera effect where you can only see clearly in front of you.

// Level 3 adapts the scene where Vincent accidentally shoots Marvin and splatters his blood all over Jules' car.
This level takes creative liberties based off of the concept of the scene.
The level involves you having to get the car to its destination without getting caught by police.
This is based off of dialogue where Jules says someone is going to notice the bloody car in broad daylight.

// If you hide the tutorial panels using "SHIFT", dialogue based off of the scene in the actual movie will start playing.

// While normally you start the game using the SPACE bar, you can actually select between the three levels using the 1, 2, and 3 keys.



//For our production of Pulp Fiction we used multiple core aspects of Phaser
- In our scenes we used:
  - Camera FX to fade in/out
  - Image and Sprite assets for Menu icons
  - TileSprites for the road backgrounds
  - Text objects for game UI and Menu instructions
  - BitmapText objects that used a custom font when we needed that Pulp Fiction flare
  - Sound effects and Music that played on certain events, like cars crashing
  - Physics Objects for all the cars, and on collision would slow the speed of the game 
  - Phaser Geometry to create a detection radius for the player's car
  - Timer Events and delayed calls to get cars spawning regularly (as well as changing the duration of an existing timer event)
  - Phaser Inputs (self explanatory)

- In our Dialog Boxes we used: 
  - Image Sprites
  - Timer Events so our text shows up on time (And can be shown letter by letter)
  - Tweens to change the alpha of the boxes when they show and disappear
  - BitmapText to get the dialog itself looking nice and custom

- In our Car objects we used:
  - All cars were extensions of Phaser physics sprites 
  - Police cars also have two Geometry circles for player detection
  - Graphics objects were used to draw and display the Circle geometry to the screen




// Sounds:
// Car driving sound effect taken from Yuarei on Youtube (https://youtu.be/cxMmWIykFd8)
// Police siren sound by guitarguy1985 on Freesound.org
// Damage sound by qubodup on Freesound.org
// Game over sound by myfox14 on Freesound.org

// Music:
// Surf Rider, written by Bob Bogle, Nole "Nokie" Edwards, Don Wilson and performed by The Lively Ories
// Misirlou, performed by Dick Dale
// Out of Limits, written by Michael Gordon and performed by The Marketts
// (Chose music from the original film's soundtrack as we felt that no other music can fit the vibe of the film.)
// (However, the tracks chosen don't necessarily coincide with how it's used in the film)
// (Instead, music was chosen based on if it fit the vibe of the level.)
*/

let config = {
  type: Phaser.AUTO,
  width: 800,
  height: 1000,
  physics: {
      default: "arcade",
      arcade: {
          debug: false
      }
  },
  scene: [Load, Title, Intro, Time, Stealth, Crash, Arrest]
}

let game = new Phaser.Game(config);

// keyboard variables
let keyUP, keyDOWN, key1, key2, key3, keyH, keyC;
let cursors = null;
